 category:"teacher",
        name: name,
        ImageUrl: url,
        yop:yop,
        linkedin:linkedin,
        git:git,
        phone:phone,
        location:location,
        dob:dob,
        gender:gender,
        skills:skills,
        college:college,
        std:std,
        end:end,
        company:company,
        tech:tech,
        position:position,
        desc:desc