export { default as Frontpg } from "./Frontpg/Frontpg";
export { default as Mainpg } from "./Mainpg/Mainpg";
export { default as Login } from "./Login/Login";
export { default as Signup } from "./Signup/Signup";
export { default as Internship } from "./Internshippg/Internship";
export { default as Jobs } from "./Jobspg/Jobs";
export { default as ResetPassword } from "./ResetPassword/ResetPassword";
export { default as Achievements } from "./Achievements/Achievements";
export {default as Detail} from "./Detail/Detail";
export { default as AchievementsInnerPage } from "./AchievementsInnerPage/AchievementsInnerPage";
export { default as UserProfile } from "./UserProfile/UserProfile";
export {default as Faultpg} from "./Faultpg/Faultpg";
export {default as Connect} from "./Connect/Connect";
export { default as Event } from "./Event/Event";
export {default as EventInnerPage} from './Event/EventInnerPage/EventInnerPage';
export {default as ConnectedUserProfile} from './ConnectedUserProfile/ConnectedUserProfile';
export {default as BarGraph} from './UserGraph/BarGraph';
export {default as PieGraph} from './UserGraph/PieGraph';
export {default as BatchWiseConnect} from './Connect/BatchWiseConnect';
export {default as Experience} from './Experience/Experience';
export {default as ExperienceInnerpg} from './Experience/ExperienceInnerpg';
export {default as VerifyUser} from './Verify/VerifyUser';